[package]
name = "quotelementa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
headless_chrome = "1"
indexmap = "1.9.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url = "2.3.1"
