[package]
name = "quotelementa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
fantoccini = "0.20.0-rc.4"
futures-util = "0.3.28"
indexmap = "1.9"
tokio = { version = "1.27", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url = "2.3.1"
